version: "3"


services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass redis
    networks:
      - pylon

  postgres:
    image: postgres:15.1
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pylon
      - POSTGRES_USER=pylon
      - POSTGRES_PASSWORD=pylon
      - POSTGRES_INITDB_ARGS=--data-checksums
    networks:
      - pylon

  pylon:
    image: getcarrier/pylon:tasknode
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: unless-stopped
    environment:
      - PYLON_CONFIG_SEED=file:/data/pylon.yml
      - REDIS_PASSWORD=redis
      - POSTGRES_DB=pylon
      - POSTGRES_USER=pylon
      - POSTGRES_PASSWORD=pylon
    volumes:
      - ./pylon:/data
    depends_on:
      - redis
      - postgres
    networks:
      - pylon
    ports:
      - 8080:8080


volumes:
  postgres-data:


networks:
  pylon:
